spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        highlight_sql: true
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.resend.com
    port: 587
    username: resend
    password: re_AJquhScs_2MZ6dkZnhMQnKxTK15N2eRye
    properties:
      mail:
        smtp.auth: true
        smtp.starttls.enable: true

jwt.secret_key: VXFMZ05uSHp2YW5uRE1ZMzVJVkRuTkJhYXArb2gwZnBqTGFqQUhuUklwaEFaamJLUFBKZWRuZHl2ZXR3a1RkUw==
confirmation_code_validity: 5